desc SQLN_EXPLAIN_PLAN
Name              Null Type           
----------------- ---- -------------- 
STATEMENT_ID           VARCHAR2(30)   
PLAN_ID                NUMBER         
TIMESTAMP              DATE           
REMARKS                VARCHAR2(4000) 
OPERATION              VARCHAR2(30)   
OPTIONS                VARCHAR2(225)  
OBJECT_NODE            VARCHAR2(128)  
OBJECT_OWNER           VARCHAR2(30)   
OBJECT_NAME            VARCHAR2(30)   
OBJECT_ALIAS           VARCHAR2(65)   
OBJECT_INSTANCE        NUMBER(38)     
OBJECT_TYPE            VARCHAR2(30)   
OPTIMIZER              VARCHAR2(255)  
SEARCH_COLUMNS         NUMBER(38)     
ID                     NUMBER(38)     
PARENT_ID              NUMBER(38)     
DEPTH                  NUMBER(38)     
POSITION               NUMBER(38)     
COST                   NUMBER(38)     
CARDINALITY            NUMBER(38)     
BYTES                  NUMBER(38)     
OTHER_TAG              VARCHAR2(255)  
PARTITION_START        VARCHAR2(255)  
PARTITION_STOP         VARCHAR2(255)  
PARTITION_ID           NUMBER(38)     
OTHER                  LONG()         
DISTRIBUTION           VARCHAR2(30)   
CPU_COST               NUMBER(38)     
IO_COST                NUMBER(38)     
TEMP_SPACE             NUMBER(38)     
ACCESS_PREDICATES      VARCHAR2(4000) 
FILTER_PREDICATES      VARCHAR2(4000) 
PROJECTION             VARCHAR2(4000) 
TIME                   NUMBER(20,2)   
QBLOCK_NAME            VARCHAR2(30)   


REM INSERTING into SQLN_EXPLAIN_PLAN
SET DEFINE OFF;
Insert into SQLN_EXPLAIN_PLAN (STATEMENT_ID,PLAN_ID,TIMESTAMP,REMARKS,OPERATION,OPTIONS,OBJECT_NODE,OBJECT_OWNER,OBJECT_NAME,OBJECT_ALIAS,OBJECT_INSTANCE,OBJECT_TYPE,OPTIMIZER,SEARCH_COLUMNS,ID,PARENT_ID,DEPTH,POSITION,COST,CARDINALITY,BYTES,OTHER_TAG,PARTITION_START,PARTITION_STOP,PARTITION_ID,OTHER,DISTRIBUTION,CPU_COST,IO_COST,TEMP_SPACE,ACCESS_PREDICATES,FILTER_PREDICATES,PROJECTION,TIME,QBLOCK_NAME) values ('D99530DA',3865,to_date('03-SEP-15','DD-MON-RR'),null,'SELECT STATEMENT','REMOTE',null,null,null,null,null,null,'ALL_ROWS',null,0,null,0,107081,107081,2096951,25163412,null,null,null,null,null,null,13223509286,106455,null,null,null,null,1285,null);
Insert into SQLN_EXPLAIN_PLAN (STATEMENT_ID,PLAN_ID,TIMESTAMP,REMARKS,OPERATION,OPTIONS,OBJECT_NODE,OBJECT_OWNER,OBJECT_NAME,OBJECT_ALIAS,OBJECT_INSTANCE,OBJECT_TYPE,OPTIMIZER,SEARCH_COLUMNS,ID,PARENT_ID,DEPTH,POSITION,COST,CARDINALITY,BYTES,OTHER_TAG,PARTITION_START,PARTITION_STOP,PARTITION_ID,OTHER,DISTRIBUTION,CPU_COST,IO_COST,TEMP_SPACE,ACCESS_PREDICATES,FILTER_PREDICATES,PROJECTION,TIME,QBLOCK_NAME) values ('D99530DA',3865,to_date('03-SEP-15','DD-MON-RR'),'<remarks><info type="nodeid/pflags">3 17</info><info type="nodeid/pflags">2 17</info><info type="db_version">11.2.0.2</info><info type="parse_schema"><![CDATA["CENTER2"]]></info><info type="plan_hash">1919083268</info><info type="plan_hash_2">3717708626</info><outline_data><hint><![CDATA[FULL(@"SEL$1" "A1"@"SEL$1")]]></hint><hint><![CDATA[OUTLINE_LEAF(@"SEL$1")]]></hint><hint><![CDATA[ALL_ROWS]]></hint><hint><![CDATA[OPT_PARAM(''_optimizer_skip_scan_enabled'' ''false'')]]></hint><hint><![CDATA[OPT_PARAM(''optimizer_dynamic_sampling'' 0)]]></hint><hint><![CDATA[DB_VERSION(''11.2.0.2'')]]></hint><hint><![CDATA[OPTIMIZER_FEATURES_ENABLE(''11.2.0.2'')]]></hint><hint><![CDATA[IGNORE_OPTIM_EMBEDDED_HINTS]]></hint></outline_data></remarks>','WINDOW','SORT',null,null,null,null,null,null,null,null,1,0,1,1,107081,2096951,25163412,null,null,null,null,null,null,13223509286,106455,42116000,null,null,'(#keys=1) "A1"."SUB_ID"[NUMBER,22], "A1"."STA_DATETIME"[DATE,7], MIN("A1"."STA_DATETIME") OVER ( PARTITION BY "A1"."SUB_ID")[7]',1285,'SEL$1');
Insert into SQLN_EXPLAIN_PLAN (STATEMENT_ID,PLAN_ID,TIMESTAMP,REMARKS,OPERATION,OPTIONS,OBJECT_NODE,OBJECT_OWNER,OBJECT_NAME,OBJECT_ALIAS,OBJECT_INSTANCE,OBJECT_TYPE,OPTIMIZER,SEARCH_COLUMNS,ID,PARENT_ID,DEPTH,POSITION,COST,CARDINALITY,BYTES,OTHER_TAG,PARTITION_START,PARTITION_STOP,PARTITION_ID,OTHER,DISTRIBUTION,CPU_COST,IO_COST,TEMP_SPACE,ACCESS_PREDICATES,FILTER_PREDICATES,PROJECTION,TIME,QBLOCK_NAME) values ('D99530DA',3865,to_date('03-SEP-15','DD-MON-RR'),null,'PARTITION RANGE','ALL',null,null,null,null,null,null,null,null,2,1,2,1,97477,2096951,25163412,null,'1','2191',2,null,null,11066633405,96953,null,null,null,'"A1"."SUB_ID"[NUMBER,22], "A1"."STA_DATETIME"[DATE,7]',1170,null);
Insert into SQLN_EXPLAIN_PLAN (STATEMENT_ID,PLAN_ID,TIMESTAMP,REMARKS,OPERATION,OPTIONS,OBJECT_NODE,OBJECT_OWNER,OBJECT_NAME,OBJECT_ALIAS,OBJECT_INSTANCE,OBJECT_TYPE,OPTIMIZER,SEARCH_COLUMNS,ID,PARENT_ID,DEPTH,POSITION,COST,CARDINALITY,BYTES,OTHER_TAG,PARTITION_START,PARTITION_STOP,PARTITION_ID,OTHER,DISTRIBUTION,CPU_COST,IO_COST,TEMP_SPACE,ACCESS_PREDICATES,FILTER_PREDICATES,PROJECTION,TIME,QBLOCK_NAME) values ('D99530DA',3865,to_date('03-SEP-15','DD-MON-RR'),null,'TABLE ACCESS','STORAGE FULL','GOLD','CUS_OWNER','SUB_CHA_PKG_HISTORY','A1@SEL$1',1,'TABLE','ANALYZED',null,3,2,3,1,97477,2096951,25163412,null,'1','2191',2,null,null,11066633405,96953,null,'"A1"."STA_DATETIME">=TO_DATE('' 2015-01-01 00:00:00'', ''syyyy-mm-dd hh24:mi:ss'')','"A1"."STA_DATETIME">=TO_DATE('' 2015-01-01 00:00:00'', ''syyyy-mm-dd hh24:mi:ss'')','"A1"."SUB_ID"[NUMBER,22], "A1"."STA_DATETIME"[DATE,7]',1170,'SEL$1');
Insert into SQLN_EXPLAIN_PLAN (STATEMENT_ID,PLAN_ID,TIMESTAMP,REMARKS,OPERATION,OPTIONS,OBJECT_NODE,OBJECT_OWNER,OBJECT_NAME,OBJECT_ALIAS,OBJECT_INSTANCE,OBJECT_TYPE,OPTIMIZER,SEARCH_COLUMNS,ID,PARENT_ID,DEPTH,POSITION,COST,CARDINALITY,BYTES,OTHER_TAG,PARTITION_START,PARTITION_STOP,PARTITION_ID,OTHER,DISTRIBUTION,CPU_COST,IO_COST,TEMP_SPACE,ACCESS_PREDICATES,FILTER_PREDICATES,PROJECTION,TIME,QBLOCK_NAME) values ('D9953159',3866,to_date('03-SEP-15','DD-MON-RR'),null,'SELECT STATEMENT','REMOTE',null,null,null,null,null,null,'ALL_ROWS',null,0,null,0,102263,102263,458110,5497320,null,null,null,null,null,null,13164222191,101640,null,null,null,null,1228,null);
Insert into SQLN_EXPLAIN_PLAN (STATEMENT_ID,PLAN_ID,TIMESTAMP,REMARKS,OPERATION,OPTIONS,OBJECT_NODE,OBJECT_OWNER,OBJECT_NAME,OBJECT_ALIAS,OBJECT_INSTANCE,OBJECT_TYPE,OPTIMIZER,SEARCH_COLUMNS,ID,PARENT_ID,DEPTH,POSITION,COST,CARDINALITY,BYTES,OTHER_TAG,PARTITION_START,PARTITION_STOP,PARTITION_ID,OTHER,DISTRIBUTION,CPU_COST,IO_COST,TEMP_SPACE,ACCESS_PREDICATES,FILTER_PREDICATES,PROJECTION,TIME,QBLOCK_NAME) values ('D9953159',3866,to_date('03-SEP-15','DD-MON-RR'),'<remarks><info type="nodeid/pflags">3 17</info><info type="nodeid/pflags">2 17</info><info type="db_version">11.2.0.2</info><info type="parse_schema"><![CDATA["CENTER2"]]></info><info type="plan_hash">2099628853</info><info type="plan_hash_2">3452733342</info><outline_data><hint><![CDATA[USE_HASH_AGGREGATION(@"SEL$1")]]></hint><hint><![CDATA[FULL(@"SEL$1" "A1"@"SEL$1")]]></hint><hint><![CDATA[OUTLINE_LEAF(@"SEL$1")]]></hint><hint><![CDATA[ALL_ROWS]]></hint><hint><![CDATA[OPT_PARAM(''_optimizer_skip_scan_enabled'' ''false'')]]></hint><hint><![CDATA[OPT_PARAM(''optimizer_dynamic_sampling'' 0)]]></hint><hint><![CDATA[DB_VERSION(''11.2.0.2'')]]></hint><hint><![CDATA[OPTIMIZER_FEATURES_ENABLE(''11.2.0.2'')]]></hint><hint><![CDATA[IGNORE_OPTIM_EMBEDDED_HINTS]]></hint></outline_data></remarks>','HASH','GROUP BY',null,null,null,null,null,null,null,null,1,0,1,1,102263,458110,5497320,null,null,null,null,null,null,13164222191,101640,42116000,null,null,'(#keys=1) "A1"."SUB_ID"[NUMBER,22], MIN("A1"."STA_DATETIME")[7]',1228,'SEL$1');
Insert into SQLN_EXPLAIN_PLAN (STATEMENT_ID,PLAN_ID,TIMESTAMP,REMARKS,OPERATION,OPTIONS,OBJECT_NODE,OBJECT_OWNER,OBJECT_NAME,OBJECT_ALIAS,OBJECT_INSTANCE,OBJECT_TYPE,OPTIMIZER,SEARCH_COLUMNS,ID,PARENT_ID,DEPTH,POSITION,COST,CARDINALITY,BYTES,OTHER_TAG,PARTITION_START,PARTITION_STOP,PARTITION_ID,OTHER,DISTRIBUTION,CPU_COST,IO_COST,TEMP_SPACE,ACCESS_PREDICATES,FILTER_PREDICATES,PROJECTION,TIME,QBLOCK_NAME) values ('D9953159',3866,to_date('03-SEP-15','DD-MON-RR'),null,'PARTITION RANGE','ALL',null,null,null,null,null,null,null,null,2,1,2,1,97477,2096951,25163412,null,'1','2191',2,null,null,11066633405,96953,null,null,null,'"A1"."SUB_ID"[NUMBER,22], "A1"."STA_DATETIME"[DATE,7]',1170,null);
Insert into SQLN_EXPLAIN_PLAN (STATEMENT_ID,PLAN_ID,TIMESTAMP,REMARKS,OPERATION,OPTIONS,OBJECT_NODE,OBJECT_OWNER,OBJECT_NAME,OBJECT_ALIAS,OBJECT_INSTANCE,OBJECT_TYPE,OPTIMIZER,SEARCH_COLUMNS,ID,PARENT_ID,DEPTH,POSITION,COST,CARDINALITY,BYTES,OTHER_TAG,PARTITION_START,PARTITION_STOP,PARTITION_ID,OTHER,DISTRIBUTION,CPU_COST,IO_COST,TEMP_SPACE,ACCESS_PREDICATES,FILTER_PREDICATES,PROJECTION,TIME,QBLOCK_NAME) values ('D9953159',3866,to_date('03-SEP-15','DD-MON-RR'),null,'TABLE ACCESS','STORAGE FULL','GOLD','CUS_OWNER','SUB_CHA_PKG_HISTORY','A1@SEL$1',1,'TABLE','ANALYZED',null,3,2,3,1,97477,2096951,25163412,null,'1','2191',2,null,null,11066633405,96953,null,'"A1"."STA_DATETIME">=TO_DATE('' 2015-01-01 00:00:00'', ''syyyy-mm-dd hh24:mi:ss'')','"A1"."STA_DATETIME">=TO_DATE('' 2015-01-01 00:00:00'', ''syyyy-mm-dd hh24:mi:ss'')','"A1"."SUB_ID"[NUMBER,22], "A1"."STA_DATETIME"[DATE,7]',1170,'SEL$1');
