SET DEFINE OFF;
CREATE USER VMS_QLXT IDENTIFIED BY 123456 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SYNONYM TO VMS_QLXT;
connect VMS_QLXT/dgnvkhdn#unu27$ec

-- vmsreport/123456

CREATE TABLE Role (
  RoleID NUMBER(24,0) PRIMARY KEY,
  Code VARCHAR(50) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  UNIQUE (Code),
  UNIQUE (Name)
);

CREATE TABLE PermissionGroup(
  PermissionGroupID NUMBER(24,0) PRIMARY KEY,
  Code VARCHAR(150) NOT NULL,
  Description VARCHAR2(200) NOT NULL,
  CONSTRAINT "PermissionGroup_UQ" UNIQUE(Code)
);

CREATE TABLE Permission (
  PermissionID NUMBER(24,0) PRIMARY KEY,
  Code VARCHAR(50) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  PermissionGroupID NUMBER(24,0) NOT NULL,
  CONSTRAINT "Permission_Code_UQ" UNIQUE (Code),
  CONSTRAINT "Permission_PermissionGroup_FK" FOREIGN KEY (PermissionGroupID) REFERENCES PermissionGroup(PermissionGroupID)
);

CREATE TABLE RoleACL (
  RoleACLID NUMBER(24,0) PRIMARY KEY,
  RoleID NUMBER(24,0) NOT NULL,
  PermissionID NUMBER(24,0) NOT NULL,
  CreatedDate TIMESTAMP NOT NULL,
  ModifiedDate TIMESTAMP,
  UNIQUE(RoleID, PermissionID),
  CONSTRAINT "RoleACL_Role_FK" FOREIGN KEY (RoleID) REFERENCES Role(RoleID),
  CONSTRAINT "RoleACL_Permission_FK" FOREIGN KEY (PermissionID) REFERENCES Permission(PermissionID)
);

CREATE TABLE Department (
  DepartmentID NUMBER(24,0) PRIMARY KEY,
  Code VARCHAR(50) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  CONSTRAINT "Department_Code_UQ" UNIQUE(Code)
);

CREATE TABLE Users(
  UserID NUMBER(24,0) PRIMARY KEY,
  UserGroupId NUMBER(24,0) NOT NULL,
  Username VARCHAR(100) NOT NULL,
  Email VARCHAR(255),
  Password VARCHAR(255) NOT NULL,
  DisplayName VARCHAR2(150) NOT NULL,
  Status INTEGER DEFAULT 1 NOT NULL,
  DepartmentID NUMBER(24,0),
  CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate TIMESTAMP DEFAULT NULL,
  LastLoginDatTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IsLDAP INTEGER NOT NULL,
  UNIQUE (DepartmentID, UserName),
  UNIQUE (Email),
  CONSTRAINT "User_Department_FK" FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID),
  CONSTRAINT "User_UserGroup_FK" FOREIGN KEY (UserGroupId) REFERENCES UserGroup(UserGroupId)
);

CREATE TABLE UserRoleACL (
  UserACLID NUMBER(24,0) PRIMARY KEY,
  UserID NUMBER(24,0) NOT NULL,
  RoleID NUMBER(24,0) NOT NULL,
  UNIQUE (UserID, RoleID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
);

CREATE TABLE UserACL (
  UserACLID NUMBER(24,0) PRIMARY KEY,
  UserID NUMBER(24,0) NOT NULL,
  PermissionID NUMBER(24,0) NOT NULL,
  UNIQUE (UserID, PermissionID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (PermissionID) REFERENCES Permission(PermissionID)
);


CREATE TABLE UserGroup (
  UserGroupID NUMBER(24,0) PRIMARY KEY,
  Code VARCHAR(50) NOT NULL,
  Description VARCHAR2(255) NOT NULL,
  UNIQUE (Code)
);

CREATE TABLE UserGroupACL (
  UserGroupACLID NUMBER(24,0) PRIMARY KEY,
  UserGroupID NUMBER(24,0) NOT NULL,
  PermissionID NUMBER(24,0) NOT NULL,
  UNIQUE(UserGroupID, PermissionID),
  CONSTRAINT "User_Group_FK" FOREIGN KEY (UserGroupID) REFERENCES UserGroup(UserGroupID),
  CONSTRAINT "User_Permission_FK" FOREIGN KEY (PermissionID) REFERENCES Permission(PermissionID)
);

CREATE SEQUENCE  Role_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  Permission_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  RoleACL_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  Department_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  Users_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  UserRoleACL_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  UserACL_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  UserGroup_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  PermissionGroup_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  UserGroupACL_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

COMMIT;

