CREATE TABLE StoreFile
  (
    StoreFileId NUMBER(24,0) PRIMARY KEY,
    MSGOITHAU NUMBER(24,0) NOT NULL,
    TypeVar VARCHAR2(255),
    FullPath VARCHAR2(255) NOT NUll,
    CREATETIME TIMESTAMP NOT NUll,
    ModifiedTime TIMESTAMP,
    UNIQUE (MSGOITHAU, TypeVar),
    CONSTRAINT "StoreFile_GOITHAU_FK" FOREIGN KEY (MSGOITHAU) REFERENCES GOITHAU(MSGOITHAU)
  );
  
  CREATE SEQUENCE  StoreFile_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
