CREATE TABLE UserGroupRoleACL (
  UserGroupRoleACLID NUMBER(24,0) PRIMARY KEY,
  UserGroupID NUMBER(24,0) NOT NULL,
  RoleID NUMBER(24,0) NOT NULL,
  UNIQUE (UserGroupID, RoleID),
  FOREIGN KEY (UserGroupID) REFERENCES UserGroup(UserGroupID),
  FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
);

CREATE SEQUENCE  UserGroupRoleACL_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

ALTER TABLE Users ADD Avatar VARCHAR(200 CHAR);
alter table USERGROUP ADD ISCENTER NUMBER(2) DEFAULT 0 NOT NULL;