--------------------------------------------------------
--  DDL for Table A_IMP_GOITHAU
--------------------------------------------------------

  CREATE TABLE A_IMP_GOITHAU
   (	STT NUMBER(24, 0),
	NGUONVON VARCHAR2(100),
	LOAI VARCHAR2(100),
	CHUTRI VARCHAR2(100),
	THANHVIEN VARCHAR2(100),
	HINHTHUC VARCHAR2(100),
	QUIMO VARCHAR2(100),
	TENPHUONGAN VARCHAR2(1000),
	TENGOITHAU VARCHAR2(1000),
	SO_PADA VARCHAR2(100),
	NGAY_PADA VARCHAR2(100),
	SO_TRINHHSMT VARCHAR2(100),
	NGAY_TRINHHSMT VARCHAR2(100),
	SO_DUYETHSMT VARCHAR2(100),
	NGAY_DUYETHSMT VARCHAR2(100),
	NGAYDANGBAO VARCHAR2(100),
	NGAYBANHS VARCHAR2(100),
	NGAYMOTHAU VARCHAR2(100),
	SO_TRINHKQ VARCHAR2(100),
	NGAY_TRINHKQ VARCHAR2(100),
	SO_DUYETKQ VARCHAR2(100),
	NGAY_DUYETKQ VARCHAR2(100),
	GIATRIGOITHAU NUMBER(24, 0),
	GIATRUNGTHAU NUMBER(24, 0),
	NHATHAUTRUNGTHAU VARCHAR2(1000),
	TINHTRANG VARCHAR2(100)
   )  ;
--------------------------------------------------------
--  DDL for Table A_IMP_NHATHAU
--------------------------------------------------------

  CREATE TABLE A_IMP_NHATHAU
   (	STT NUMBER(24, 0),
	GOITHAU VARCHAR2(1000),
	NHATHAU VARCHAR2(1000)
   ) ;

   --------------------------------------------------------
--  DDL for Table DATA_ACTION
--------------------------------------------------------

  CREATE TABLE DATA_ACTION
   (	PHONENUMBER VARCHAR2(100 BYTE),
	EMAIL VARCHAR2(100 BYTE),
	SMSCONTENT VARCHAR2(1000 BYTE),
	EMAILCONTENT VARCHAR2(4000 BYTE),
	ACTIONDATE DATE DEFAULT SYSDATE,
	TENNGUOINHAN VARCHAR2(1000 BYTE),
	IS_SMS NUMBER,
	IS_EMAILED NUMBER,
	FLAG_MAIL NUMBER,
	FLAG_SMS NUMBER,
	DATE_MAIL DATE,
	DATE_SMS DATE
   )  ;

   --------------------------------------------------------
--  DDL for Table DATA_CONVERT
--------------------------------------------------------

  CREATE TABLE DATA_CONVERT
   (	SOURCE VARCHAR2(4000 BYTE),
	DESTINATION VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;

  --------------------------------------------------------
--  DDL for Table LOG
--------------------------------------------------------

  CREATE TABLE LOG
   (	USERID NUMBER,
	TEN VARCHAR2(200 BYTE),
	COMPUTER_NAME VARCHAR2(200 BYTE),
	IP_ADDRESS VARCHAR2(15 BYTE),
	NGAYTHAOTAC DATE DEFAULT sysdate,
	DOITUONG VARCHAR2(500 BYTE),
	HANHDONG VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;

--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE MENU
   (	MSMENU NUMBER,
	MSMENU_PARENT NUMBER DEFAULT -1,
	MENU_URL VARCHAR2(500 BYTE),
	DESCRIPTION VARCHAR2(500 BYTE),
	TENMENU VARCHAR2(500 BYTE),
	STT_MENU NUMBER DEFAULT 0,
	MENU_TYPE NUMBER DEFAULT 0,
	JSP_PAGENAME VARCHAR2(300 BYTE),
	ISHIDDEN VARCHAR2(1 BYTE) DEFAULT 1,
	ISDISABLE VARCHAR2(1 BYTE),
	ICON VARCHAR2(100 BYTE),
	LINKTYPE VARCHAR2(1 BYTE),
	WIDTH NUMBER,
	HEIGHT NUMBER,
	ACTIVE NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table MENU_PROPERTY
--------------------------------------------------------

  CREATE TABLE MENU_PROPERTY
   (	MS_PK NUMBER,
	MSMENU NUMBER,
	PROPERTY_TYPE VARCHAR2(50 BYTE),
	THAMSO VARCHAR2(500 BYTE),
	GIATRITHAMSO VARCHAR2(1000 BYTE),
	GHICHU VARCHAR2(512 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;