alter table Department add ChuThich varchar(512 char);
alter table Department add Active number(1,0);
alter table Department add STT_PB number;
alter table Department add MSPhanLoaiPhongBan number;
 COMMENT ON COLUMN Department.MSPHANLOAIPHONGBAN IS '1:  Ky Thuat 2: Kinh Doanh';
alter table Department add STT_PB_BL number;




CREATE TABLE ATTACH_FILE(
  ATTACHID NUMBER(24, 0) PRIMARY KEY,
  MSTAILIEU NUMBER(24, 0),
  LOAI VARCHAR2(500),
  TENGOC VARCHAR2(500),
  TENUPLOAD VARCHAR2(500),
  DUONGDAN VARCHAR2(500),
  KICHTHUOC VARCHAR2(100),
  USERID NUMBER(24, 0),
  ACTIVE NUMBER(1, 0),
  CONSTRAINT "Attach_File_User_FK" FOREIGN KEY (USERID) REFERENCES Users(UserID)
) ;
CREATE SEQUENCE ATTACH_FILE_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table BOPHAN
--------------------------------------------------------

CREATE TABLE BOPHAN(
  MSBOPHAN NUMBER(24, 0) PRIMARY KEY,
  TENBOPHAN VARCHAR2(50 BYTE),
  ACTIVE NUMBER(1,0),
  GHICHU VARCHAR2(100 BYTE),
  DEPARTMENTID NUMBER(24, 0),
  MABOPHAN VARCHAR2(50 BYTE),
  CONSTRAINT "BOPHAN_DEPARTMENT_FK" FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID)
) ;
CREATE SEQUENCE BOPHAN_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DANGBAO
--------------------------------------------------------

CREATE TABLE DANGBAO(
  MSDANGBAO NUMBER(24, 0) PRIMARY KEY,
  MSGOITHAU NUMBER(24, 0),
  MSNOIDUNG NUMBER(24, 0),
  NGAYDANGBAO DATE,
  GHICHU VARCHAR2(1000 BYTE),
  SOBAOBATDAU NUMBER,
  SOKYDANGBAO NUMBER,
  SOCONGVAN VARCHAR2(500 BYTE),
  NGAYCONGVAN DATE,
  MSLOAIBAO NUMBER(24, 0),
  CONSTRAINT "DANGBAO_GOITHAU_FK" FOREIGN KEY (MSGOITHAU) REFERENCES GOITHAU(MSGOITHAU),
  CONSTRAINT "DANGBAO_NOIDUNG_FK" FOREIGN KEY (MSNOIDUNG) REFERENCES DM_NOIDUNG(MSNOIDUNG),
  CONSTRAINT "DANGBAO_LOAIBAO_FK" FOREIGN KEY (MSLOAIBAO) REFERENCES DM_LOAIBAO(MSLOAIBAO)
) ;
CREATE SEQUENCE DANGBAO_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table DM_GIAIDOAN
--------------------------------------------------------

CREATE TABLE DM_GIAIDOAN(
  MSGIAIDOAN NUMBER(24, 0) PRIMARY KEY,
  TENGIAIDOAN VARCHAR2(100),
  STT NUMBER,
  GHICHU VARCHAR2(500)
) ;
CREATE SEQUENCE DM_GIAIDOAN_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_HINHTHUCGT
--------------------------------------------------------

CREATE TABLE DM_HINHTHUCGT(
  MSHINHTHUC NUMBER(24, 0) PRIMARY KEY,
  MAHINHTHUC VARCHAR2(100),
  TENHINHTHUC VARCHAR2(100),
  STT NUMBER,
  GHICHU VARCHAR2(500)
);
CREATE SEQUENCE DM_HINHTHUCGT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_LANHDAO
--------------------------------------------------------

CREATE TABLE DM_LANHDAO(
  MSLANHDAO NUMBER(24, 0) PRIMARY KEY,
  TENLANHDAO VARCHAR2(100),
  STT NUMBER,
  GHICHU VARCHAR2(500),
  ACTIVE NUMBER(1,0),
  CHUCVU VARCHAR2(500)
) ;
CREATE SEQUENCE DM_LANHDAO_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_LOAI
--------------------------------------------------------

CREATE TABLE DM_LOAI(
  MSLOAI NUMBER(24, 0) PRIMARY KEY,
  TENLOAI VARCHAR2(100),
  STT NUMBER,
  GHICHU VARCHAR2(500),
  ACTIVE NUMBER(1, 0),
  MALOAI VARCHAR2(1000 BYTE)
) ;
CREATE SEQUENCE DM_LOAI_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_LOAIBAO
--------------------------------------------------------

CREATE TABLE DM_LOAIBAO(
  MSLOAIBAO NUMBER(24, 0) PRIMARY KEY,
  TENLOAIBAO VARCHAR2(100),
  STT NUMBER,
  GHICHU VARCHAR2(500),
  MALOAIBAO VARCHAR2(100)
) ;
CREATE SEQUENCE DM_LOAIBAO_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_LOAIBIEUMAU
--------------------------------------------------------

  CREATE TABLE DM_LOAIBIEUMAU
   (	MSBIEUMAU  NUMBER(24, 0) PRIMARY KEY,
	TENBIEUMAU VARCHAR2(100),
	STT NUMBER,
	GHICHU VARCHAR2(500)
   ) ;
   CREATE SEQUENCE DM_LOAIBIEUMAU_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_NGUONVON
--------------------------------------------------------

  CREATE TABLE DM_NGUONVON
   (	MSNGUONVON NUMBER(24, 0) PRIMARY KEY,
	TENNGUONVON VARCHAR2(100),
	STT NUMBER,
	GHICHU VARCHAR2(500)
   ) ;
    CREATE SEQUENCE DM_NGUONVON_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_NHATHAU
--------------------------------------------------------

  CREATE TABLE DM_NHATHAU
   (	MSNHATHAU NUMBER(24, 0) PRIMARY KEY,
	TENNHATHAU VARCHAR2(100),
	DIACHI VARCHAR2(500),
	DIENTHOAI VARCHAR2(100),
	FAX VARCHAR2(100),
	GHICHU VARCHAR2(500),
	ACTIVE NUMBER,
	MASOTHUE VARCHAR2(100)
   )  ;
    CREATE SEQUENCE DM_NHATHAU_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_NOIDUNG
--------------------------------------------------------

  CREATE TABLE DM_NOIDUNG
   (	MSNOIDUNG NUMBER(24, 0) PRIMARY KEY,
	TENNOIDUNG VARCHAR2(100),
	STT NUMBER,
	GHICHU VARCHAR2(500),
	LOAI NUMBER
   ) ;
   CREATE SEQUENCE DM_NOIDUNG_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_NOIDUNGHOSO
--------------------------------------------------------

  CREATE TABLE DM_NOIDUNGHOSO
   (	MSNOIDUNGHS NUMBER(24, 0) PRIMARY KEY,
	TENNOIDUNGHS VARCHAR2(1000),
	STT NUMBER,
	ACTIVE NUMBER(1,0),
	MSHINHTHUC NUMBER(24, 0),
	ISGIATHAU NUMBER,
	  CONSTRAINT "DM_NOIDUNGHOSO_HINHTHUC_FK" FOREIGN KEY (MSHINHTHUC) REFERENCES DM_HINHTHUCGT(MSHINHTHUC)
   ) ;
    CREATE SEQUENCE DM_NOIDUNGHOSO_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_QUIMO
--------------------------------------------------------

  CREATE TABLE DM_QUIMO
   (	MSQUIMO NUMBER(24, 0) PRIMARY KEY,
	TENQUIMO VARCHAR2(100),
	STT NUMBER,
	GHICHU VARCHAR2(500)
   )  ;
   CREATE SEQUENCE DM_QUIMO_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_THAMSOGUIMAIL
--------------------------------------------------------

  CREATE TABLE DM_THAMSOGUIMAIL
   (	MSTHAMSOGUIMAIL NUMBER(24, 0) PRIMARY KEY,
	MSHINHTHUC NUMBER(24, 0),
	MSQUIMO NUMBER(24, 0),
	SONGAYQUIDINH NUMBER DEFAULT 0,
	SONGAYDENHAN NUMBER,
	MSGIAIDOAN NUMBER(24, 0) ,
	CONSTRAINT "DM_THAMSOGUIMAIL_HINHTHUC_FK" FOREIGN KEY (MSHINHTHUC) REFERENCES DM_HINHTHUCGT(MSHINHTHUC),
	CONSTRAINT "DM_THAMSOGUIMAIL_QUIMO_FK" FOREIGN KEY (MSQUIMO) REFERENCES DM_QUIMO(MSQUIMO),
	CONSTRAINT "DM_THAMSOGUIMAIL_GIAIDOAN_FK" FOREIGN KEY (MSGIAIDOAN) REFERENCES DM_GIAIDOAN(MSGIAIDOAN)
   ) ;
    CREATE SEQUENCE DM_THAMSOGUIMAIL_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_THAMSOHETHONG
--------------------------------------------------------

  CREATE TABLE DM_THAMSOHETHONG
   (	MSTHAMSOHETHONG NUMBER(24, 0) PRIMARY KEY,
	TENTHAMSOHETHONG VARCHAR2(100 BYTE),
	GIATRI VARCHAR2(500 BYTE),
	GHICHU VARCHAR2(100 BYTE),
	ACTIVE NUMBER(1,0)
   ) ;
   CREATE SEQUENCE DM_THAMSOHETHONG_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_THAMSOHETHONG_BK
--------------------------------------------------------

  CREATE TABLE DM_THAMSOHETHONG_BK
   (	MSTHAMSOHETHONG NUMBER(24, 0) PRIMARY KEY,
	TENTHAMSOHETHONG VARCHAR2(100 BYTE),
	GIATRI VARCHAR2(500 BYTE),
	GHICHU VARCHAR2(100 BYTE),
	ACTIVE NUMBER(1,0)
   )  ;
   CREATE SEQUENCE DM_THAMSOHETHONG_BK_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_THAMSOQUIMO
--------------------------------------------------------

  CREATE TABLE DM_THAMSOQUIMO
   (	MSTHAMSO NUMBER(24, 0) PRIMARY KEY,
	MSTINHCHAT NUMBER(24, 0),
	FROMVALUE NUMBER,
	TOVALUE NUMBER,
	MSQUIMO NUMBER(24, 0),
	CONSTRAINT "DM_THAMSOQUIMO_TINHCHAT_FK" FOREIGN KEY (MSTINHCHAT) REFERENCES DM_TINHCHATGT(MSTINHCHAT),
	CONSTRAINT "DM_THAMSOQUIMO_QUIMO_FK" FOREIGN KEY (MSQUIMO) REFERENCES DM_QUIMO(MSQUIMO)
   ) ;
    CREATE SEQUENCE DM_THAMSOQUIMO_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_TINHCHATGT
--------------------------------------------------------

  CREATE TABLE DM_TINHCHATGT
   (	MSTINHCHAT NUMBER(24, 0) PRIMARY KEY,
	TENTINHCHAT VARCHAR2(100),
	STT NUMBER,
	GHICHU VARCHAR2(500)
   )  ;
   CREATE SEQUENCE DM_TINHCHATGT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DM_TINHTRANG
--------------------------------------------------------

  CREATE TABLE DM_TINHTRANG
   (	MSTINHTRANG NUMBER(24, 0) PRIMARY KEY,
	TENTINHTRANG VARCHAR2(100 BYTE),
	ACTIVE NUMBER(1,0),
	MATINHTRANG VARCHAR2(100 BYTE),
	GHICHU VARCHAR2(100 BYTE)
   ) ;
    CREATE SEQUENCE DM_TINHTRANG_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table GOITHAU
--------------------------------------------------------

  CREATE TABLE GOITHAU
   (	MSGOITHAU NUMBER(24, 0) PRIMARY KEY,
	MAGOITHAU NUMBER(24, 0),
	TENGOITHAU VARCHAR2(500),
	NOIDUNG VARCHAR2(4000 BYTE),
	GIATRIGOITHAU NUMBER,
	SONAMHD NUMBER,
	SOTHANGHD NUMBER,
	SONGAYHD NUMBER,
	MSQUIMO NUMBER(24, 0),
	MSNGUONVON NUMBER(24, 0),
	TENPADA VARCHAR2(1000),
	MSLOAI NUMBER(24, 0),
	DEPARTMENTID NUMBER(24, 0),
	MSLANHDAO NUMBER(24, 0),
	MSHINHTHUC NUMBER(24, 0),
	MSTINHCHAT NUMBER(24, 0),
	MSTINHTRANG NUMBER(24, 0),
	SOQD VARCHAR2(500),
	NGAYQD DATE,
	CREATER VARCHAR2(500),
	CREATETIME DATE,
	EDITER VARCHAR2(500),
	EDITTIME DATE,
	GIABANHSMT NUMBER,
	BAODAMDUTHAU NUMBER,
	GHICHU VARCHAR2(500),
	LANDAUTHAU NUMBER,
	MSGOITHAUREF NUMBER(24, 0),
	SOCV_TRINHPD VARCHAR2(500),
	NGAYCV_TRINHPD DATE,
  MSNHANVIEN_CVTD NUMBER,
	CONSTRAINT "GOITHAU_DM_QUIMO_FK" FOREIGN KEY (MSQUIMO) REFERENCES DM_QUIMO(MSQUIMO),
	CONSTRAINT "GOITHAU_DM_NGUONVON_FK" FOREIGN KEY (MSNGUONVON) REFERENCES DM_NGUONVON(MSNGUONVON),
	CONSTRAINT "GOITHAU_DM_LOAI_FK" FOREIGN KEY (MSLOAI) REFERENCES DM_LOAI(MSLOAI),
	CONSTRAINT "GOITHAU_DEPARTMENT_FK" FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID),
	CONSTRAINT "GOITHAU_DM_HINHTHUCGT_FK" FOREIGN KEY (MSHINHTHUC) REFERENCES DM_HINHTHUCGT(MSHINHTHUC),
	CONSTRAINT "GOITHAU_DM_TINHCHATGT_FK" FOREIGN KEY (MSTINHCHAT) REFERENCES DM_TINHCHATGT(MSTINHCHAT),
	CONSTRAINT "GOITHAU_USERID_FK" FOREIGN KEY (MSNHANVIEN_CVTD) REFERENCES USER(USERID),
	CONSTRAINT "GOITHAU_DM_TINHTRANG_FK" FOREIGN KEY (MSTINHTRANG) REFERENCES DM_TINHTRANG(MSTINHTRANG)
   ) ;

  CREATE SEQUENCE GOITHAU_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table GOITHAU_NHANVIEN
--------------------------------------------------------

  CREATE TABLE GOITHAU_NHANVIEN
   (	MSGOITHAU_NV NUMBER(24, 0) PRIMARY KEY,
	MSGOITHAU NUMBER(24, 0),
	UserID NUMBER(24, 0),
	ISCHUTRI NUMBER(1,0) DEFAULT 0  ,
		CONSTRAINT "GOITHAU_NHANVIEN_GOITHAU_FK" FOREIGN KEY (MSGOITHAU) REFERENCES GOITHAU(MSGOITHAU),
		CONSTRAINT "GOITHAU_NHANVIEN_USERS_FK" FOREIGN KEY (UserID) REFERENCES USERS(UserID)
   )  ;
   CREATE SEQUENCE GOITHAU_NHANVIEN_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table GOITHAU_NHATHAU
--------------------------------------------------------

  CREATE TABLE GOITHAU_NHATHAU
   (	MSGOITHAU NUMBER(24, 0),
	TENNHATHAU VARCHAR2(1000),
	DIACHI VARCHAR2(1000),
	DIENTHOAI VARCHAR2(1000),
	FAX VARCHAR2(1000),
	NGAYMUAHS DATE,
	NGAYNOPHS DATE,
	GIATHAU NUMBER,
	ISTRUNGTHAU NUMBER(1,0),
	MSGOITHAU_NT NUMBER(24, 0) PRIMARY KEY,
	MSNHATHAU NUMBER(24, 0),
	CONSTRAINT "GOITHAU_NHATHAU_DM_NHATHAU_FK" FOREIGN KEY (MSNHATHAU) REFERENCES DM_NHATHAU(MSNHATHAU),
	CONSTRAINT "GOITHAU_NHATHAU_GOITHAU_FK" FOREIGN KEY (MSGOITHAU) REFERENCES GOITHAU(MSGOITHAU)
   )  ;
   CREATE SEQUENCE GOITHAU_NHATHAU_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table HOSOLUUTRU
--------------------------------------------------------

  CREATE TABLE HOSOLUUTRU
   (	MSGOITHAU NUMBER(24, 0),
	SOTU NUMBER,
	SOKE NUMBER,
	GHICHU VARCHAR2(1000),
	CREATER VARCHAR2(50),
	CREATETIME DATE,
	EDITER VARCHAR2(50),
	EDITTIME DATE,
	MSLUUTRU NUMBER(24, 0) PRIMARY KEY,
	CONSTRAINT "HOSOLUUTRU_GOITHAU_FK" FOREIGN KEY (MSGOITHAU) REFERENCES GOITHAU(MSGOITHAU)
   )  ;
   CREATE SEQUENCE HOSOLUUTRU_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table HOSOTHAU
--------------------------------------------------------

  CREATE TABLE HOSOTHAU
   (	MSHOSOTHAU NUMBER(24, 0) PRIMARY KEY,
	MSGOITHAU_NT NUMBER(24, 0),
	MSNOIDUNGHS NUMBER(24, 0),
	GHICHU VARCHAR2(1000 BYTE) ,
	CONSTRAINT "HOSOTHAU_GOITHAU_NHATHAU_FK" FOREIGN KEY (MSGOITHAU_NT) REFERENCES GOITHAU_NHATHAU(MSGOITHAU_NT),
	CONSTRAINT "HOSOTHAU_DM_NOIDUNGHOSO_FK" FOREIGN KEY (MSNOIDUNGHS) REFERENCES DM_NOIDUNGHOSO(MSNOIDUNGHS)
   )  ;
   CREATE SEQUENCE HOSOTHAU_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table KINHPHI
--------------------------------------------------------

  CREATE TABLE KINHPHI
   (	MSKINHPHI NUMBER(24, 0) PRIMARY KEY,
	MSGOITHAU NUMBER(24, 0),
	MSLOAIBAO NUMBER(24, 0),
	MSNOIDUNG NUMBER(24, 0),
	SOKY NUMBER,
	CHIPHI NUMBER,
	THANHTIEN NUMBER,
	KHOBAO VARCHAR2(500),
	CONSTRAINT "KINHPHI_GOITHAU_FK" FOREIGN KEY (MSGOITHAU) REFERENCES GOITHAU(MSGOITHAU),
	CONSTRAINT "KINHPHI_DM_LOAIBAO_FK" FOREIGN KEY (MSLOAIBAO) REFERENCES DM_LOAIBAO(MSLOAIBAO),
	CONSTRAINT "KINHPHI_DM_NOIDUNG_FK" FOREIGN KEY (MSNOIDUNG) REFERENCES DM_NOIDUNG(MSNOIDUNG)
   ) ;
   CREATE SEQUENCE KINHPHI_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


alter table users add manhanvien varchar(15 byte);
alter table users add tennhanvien varchar(100 byte);
alter table users add honhanvien varchar(100 byte);
alter table users add ngaysinh date;
alter table users add ngayvaovms date;
alter table users add ngayravms date;
alter table users add cmnd varchar(10 byte);
alter table users add gioitinh number(1,0);
alter table users add dienthoai varchar2(50 BYTE);
alter table users add dienthoaidd varchar2(50 BYTE);
alter table users add somaynhanh varchar2(5 byte);
alter table users add dienthoaicongty varchar2(50 byte);
alter table users add stt_bl number default 1;
alter table users add stt_hs number default 1;
alter table users add last_userid_update varchar(100 byte);
alter table users add msbophan number(24, 0);
alter table users add constraints users_bophan_fk foreign key (msbophan) REFERENCES BOPHAN(msbophan) ;
alter table users add ghichu varchar2(1000 BYTE);
alter table users add nhansms number default 1;
alter table users add nhanemail number default 1;
alter table users add machungtu varchar(5 byte);
alter table users add chuyennganh varchar2(1000 byte);
alter table users add tenviettat varchar2(500 byte);
alter table users add istotruong number(1, 0);


--------------------------------------------------------
--  DDL for Table TIENDO
--------------------------------------------------------

  CREATE TABLE TIENDO
   (	MSTIENDO NUMBER(24, 0) PRIMARY KEY,
	MSGOITHAU NUMBER(24, 0),
	TCG_SO VARCHAR2(1000 BYTE),
	TCG_NGAY DATE,
	TRINHHS_SO VARCHAR2(1000 BYTE),
	TRINHHS_NGAY DATE,
	DUYETHS_SO VARCHAR2(1000 BYTE),
	DUYETHS_NGAY DATE,
	TRINHDANGBAO_SO VARCHAR2(1000 BYTE),
	TRINHDANGBAO_NGAY DATE,
	NGAYBANHS_L1 DATE,
	NGAYBANHS_L2 DATE,
	NGAYBANHS_L3 DATE,
	NGAYMOTHAU_L1 DATE,
	NGAYMOTHAU_L2 DATE,
	NGAYMOTHAU_L3 DATE,
	NGAYDONGTHAU_L1 DATE,
	NGAYDONGTHAU_L2 DATE,
	NGAYDONGTHAU_L3 DATE,
	TRINHKQ_SO VARCHAR2(1000 BYTE),
	TRINHKQ_NGAY DATE,
	PHEDUYETKQ_SO VARCHAR2(1000 BYTE),
	PHEDUYETKQ_NGAY DATE,
	THONGBAOKQ_SO VARCHAR2(1000 BYTE),
	THONGBAOKQ_NGAY DATE,
	GHICHU VARCHAR2(1000 BYTE),
	CREATER VARCHAR2(1000),
	CREATIME DATE,
	EDITER VARCHAR2(1000),
	EDITTIME DATE,
	ISHUYTHAU NUMBER,
	CDT_SO VARCHAR2(100 BYTE),
	CDT_NGAY DATE,
	BAOCAODG_SO VARCHAR2(1000 BYTE),
	BAOCAODG_NGAY DATE,
	TRINHTCG_SO VARCHAR2(500),
	TRINHTCG_NGAY DATE,
		CONSTRAINT "TIENDO_GOITHAU_FK" FOREIGN KEY (MSGOITHAU) REFERENCES GOITHAU(MSGOITHAU)
   ) ;
    CREATE SEQUENCE TIENDO_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;



alter table tiendo add thamdinhpa_so VARCHAR2(1000 BYTE);
alter table tiendo add thamdinhpa_ngay DATE;
alter table tiendo add qdpheduyet_so VARCHAR2(1000 BYTE);
alter table tiendo add qdpheduyet_ngay DATE;
alter table tiendo add dbkehoachthau_so VARCHAR2(1000 BYTE);
alter table tiendo add dbkehoachthau_ngay DATE;
alter table tiendo add dbkqluachonnhathau_so VARCHAR2(1000 BYTE);
alter table tiendo add dbkqluachonnhathau_ngay DATE;
alter table tiendo add baocaothamdinh_so VARCHAR2(1000 BYTE);
alter table tiendo add baocaothamdinh_ngay DATE;
alter table tiendo add thumoithuongthao_so VARCHAR2(1000 BYTE);
alter table tiendo add thumoithuongthao_ngay DATE;
alter table tiendo add bienbanthuongthao_so VARCHAR2(1000 BYTE);
alter table tiendo add bienbanthuongthao_ngay DATE;
alter table tiendo add bcthamdinhketqua_so VARCHAR2(1000 BYTE);
alter table tiendo add bcthamdinhketqua_ngay DATE;

alter table dm_nhathau add oldid number(24, 0);
alter table dm_nhathau add constraints dm_nhathau_OLD_fk foreign key (oldid) REFERENCES dm_nhathau(msnhathau) ;


alter table dm_noidunghoso add tinhtrangniemphong varchar(1000 byte);
alter table dm_noidunghoso add soluongbangoc integer;
alter table dm_noidunghoso add soluongbanchup integer;
alter table dm_noidunghoso add thoigiancohieuluc varchar(1000 byte);
alter table dm_noidunghoso add giaduthau float;
alter table dm_noidunghoso add giamgia float;
alter table dm_noidunghoso add hinhthuc_giatri_thoihan varchar(1000 byte);
alter table dm_noidunghoso add thoigianthuchien varchar(1000 byte);
alter table dm_noidunghoso add dieukienthanhtoan varchar(1000 byte);
alter table dm_noidunghoso add giayphepbanhang varchar(1000 byte);
alter table dm_noidunghoso add baohanh varchar(1000 byte);
alter table dm_noidunghoso add nhanhieu varchar(1000 byte);

  CREATE TABLE DM_LOAIBIEUMAUFIELD(
      MSBIEUMAUFIELD NUMBER(24, 0) PRIMARY KEY,
      MSBIEUMAU NUMBER(24,0),
      FIELDNAME VARCHAR(255 BYTE),
      FIELDTYPE VARCHAR(255 BYTE),
      COLUMNNUM NUMBER (38,0),
    CONSTRAINT "DM_LOAIBIEUMAUFIELD_BIEUMAU_FK" FOREIGN KEY (MSBIEUMAU) REFERENCES DM_LOAIBIEUMAU(MSBIEUMAU)
   ) ;
    CREATE SEQUENCE DM_LOAIBIEUMAUFIELD_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

  CREATE TABLE DM_LOAIBIEUMAUFIELD_FIELD(
      MSBMFIELDFIELD NUMBER(24, 0) PRIMARY KEY,
      MSBIEUMAUFIELD NUMBER(24,0),
      FIELDTYPE VARCHAR(255 BYTE),
      GETFIELD VARCHAR(255 BYTE),
    CONSTRAINT "DM_LOAIBMFIELD_FIELD_BM_FK" FOREIGN KEY (MSBIEUMAUFIELD) REFERENCES DM_LOAIBIEUMAUFIELD(MSBIEUMAUFIELD)
   ) ;
    CREATE SEQUENCE DM_LOAIBMFIELD_FIELD_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

